// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENrK4ExQQ_zF8446bY4FHdJsZcuh8woo',
    appId: '1:826069435270:web:ae7c18713b6342e2dfe207',
    messagingSenderId: '826069435270',
    projectId: 'ecanteen-be268',
    authDomain: 'ecanteen-be268.firebaseapp.com',
    storageBucket: 'ecanteen-be268.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJvwYGnHtTtqAH1re7QJ9hKuxomaFtLw',
    appId: '1:826069435270:android:904534c47bf74515dfe207',
    messagingSenderId: '826069435270',
    projectId: 'ecanteen-be268',
    storageBucket: 'ecanteen-be268.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8aNnbW2nmc-VARa330g9kZ7Sr_wfJlQ',
    appId: '1:826069435270:ios:ba0181e865530fa4dfe207',
    messagingSenderId: '826069435270',
    projectId: 'ecanteen-be268',
    storageBucket: 'ecanteen-be268.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn8aNnbW2nmc-VARa330g9kZ7Sr_wfJlQ',
    appId: '1:826069435270:ios:ba0181e865530fa4dfe207',
    messagingSenderId: '826069435270',
    projectId: 'ecanteen-be268',
    storageBucket: 'ecanteen-be268.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENrK4ExQQ_zF8446bY4FHdJsZcuh8woo',
    appId: '1:826069435270:web:dbaea4643d1247a5dfe207',
    messagingSenderId: '826069435270',
    projectId: 'ecanteen-be268',
    authDomain: 'ecanteen-be268.firebaseapp.com',
    storageBucket: 'ecanteen-be268.firebasestorage.app',
  );
}
